# Pipeline variables
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -Dmaven.repo.local=.m2/repository --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_OPTIONS: "--max-old-space-size=8192"
  

# Cache policy - Share target folders between jobs - Note that key is related to a commit and is purged automatically after pipeline execution
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/.m2/repository/**/*
    - $CI_PROJECT_DIR/**/target/**/*

include:
  - project: 'boost/template-ci/pipelines/common'
    file: 'docker/docker-template.yml'
  - project: 'boost/template-ci/pipelines/common'
    file: 'securite/oss-index/oss-index-template.yml' 

default:
  image: maven:3.6.0-jdk-11
  before_script:
    - apt update && apt install -y gettext-base build-essential
    - envsubst '${MVN_GROUP} ${MVN_RELEASE} ${MVN_SNAPSHOTS}' < pom.xml > pom.subst && mv -f pom.subst pom.xml

# Stages definition
stages:
  - build
  - test
  - sast
  - deploy

# Build job with maven plugin execution policies define in parent pom
.urb:build:
  script:
    - mvn $MAVEN_CLI_OPTS -U clean package ${OPTS} -Pprod
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR//target/urbanisme*.war
      - $CI_PROJECT_DIR//target/urbanisme*.zip
 
urb:build:
  extends: .urb:build
  except:
    refs:
      - master
      - open/master  
  tags: 
   - iaas
      
urb:build:master:
  extends: .urb:build
  only:
    refs:
      - master
      - open/master   
  variables:
    OPTS: "-DskipTests"  

# Sonar code quality analysis - note a full test coverage report through a jacoco.exec merged file in base project folder
.urb:sonar:
  stage: test
  allow_failure: true
  script:
    - >
      mvn $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
      ${BRANCH}

urb:sonar:
  extends: .urb:sonar
  dependencies:
    - urb:build
  except:
    refs:
      - master
      - open/master
  variables:
    BRANCH: -Dsonar.branch.name=$CI_COMMIT_REF_NAME
            

# On master, do not use branch parameter
urb:sonar:master:
  extends: .urb:sonar
  dependencies:
    - urb:build:master
  only:
    refs:
      - master
      - open/master

.urb:deploy:
  stage: deploy
  image: glregistry.boost.open.global/boost/docker/mvn-node-jdk11-ansible:latest
  cache: {}
  tags:
    - iaas
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ansible_private_key" | base64 -d)
  script:
    - ls $CI_PROJECT_DIR/target/
    - find $CI_PROJECT_DIR/target/ -name "urbanisme*.war" -exec cp {} $CI_PROJECT_DIR/ansible/dockerize/files/addon_urbanisme.war \;
    - find $CI_PROJECT_DIR/target/ -name "urbanisme*.zip" -exec cp {} $CI_PROJECT_DIR/ansible/dockerize/files/addon_urbanisme.zip \;
    - cd $CI_PROJECT_DIR/ansible
    - cp ${ANSIBLE_VAR_FILE} $HOME/addon_urbanisme_var.yml
    - ansible-playbook addon_urbanisme-docker.yml -v -i "${SERVER}," -u root --ssh-common-args=-oStrictHostKeyChecking=no

urb:deploy:
  extends: .urb:deploy
  dependencies:
    - urb:build
  only:
    refs:
      - open/develop
  variables:
    SERVER: "REN1VML0096"
    ANSIBLE_VAR_FILE: addon_urbanisme_dev_var.yml

urb:deploy:master:
  extends: .urb:deploy
  dependencies:
    - urb:build:master
  only:
    refs:
      - open/master
  variables:
    SERVER: "REN1VML0095"
    ANSIBLE_VAR_FILE: addon_urbanisme_rct_var.yml
   