image:
  tag: open-develop
  env:
    - name: URBANISME_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: urbanisme-secret-qua
          key: database.urbanisme.password
    - name: URBANISME_BDD_HOST
      value: 127.0.0.1
      
    - name: SWAGGER_SERVER
      value: https://search-application-qua.shom-search.karbon.open.global/