apiVersion: v1
kind: Secret
metadata:
  name: urbanisme-secret-qua
  labels:
    app.kubernetes.io/instance: urbanisme-secret-qua
    app.kubernetes.io/name: urbanisme-secret-qua
    environnement: qua
type: Opaque
data:
  database.urbanisme.password: dXJiYW5pc21l
  database.cadastrapp.password: Y2FkYXN0cmFwcA==