---
# create root directory
- name: Creates directory application
  file:
    state: directory
    mode: 0775
    path: "{{ item }}"
  with_items:
    - "{{addon_urbanisme_image_directory}}/"
    - "{{addon_urbanisme_addon_directory}}"
    - "{{addon_urbanisme_image_directory}}/addon_urbanisme"
    - "{{addon_urbanisme_config_directory}}/urbanisme"
    - "{{addon_urbanisme_config_directory}}/urbanisme/templates"
        
# copy addon
- name: Copy addon to mapfishapp
  unarchive:
    src: "src/docker/mapfishapp/urbanisme-addon.zip"
    dest: "{{addon_urbanisme_addon_directory}}"
    remote_src: no
    mode: 0775

# update security proxy
- name: Check whether targets-mapping.properties contains addon_urbanisme
  command: grep -Fcq "addon_urbanisme" "{{ addon_urbanisme_config_directory }}/security-proxy/targets-mapping.properties"
  register: checksecurityaddon_urbanisme
  check_mode: no
  ignore_errors: true
  changed_when: no

- name: Update targets-mapping.properties if needed
  when: checksecurityaddon_urbanisme.rc == 1
  shell:
    cmd: echo "urbanisme=http://addon_urbanisme:{{addon_urbanisme_server_port}}/urbanisme" >> "{{ addon_urbanisme_config_directory }}/security-proxy/targets-mapping.properties"    

# copy images 
- name: Copy addon_urbanisme api Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ addon_urbanisme_image_directory }}/Dockerfile"
    mode: 0770
    
- name: Copy addon_urbanisme war
  copy:
    src: "{{ addon_urbanisme_war_name }}"
    dest: "{{ addon_urbanisme_image_directory }}/addon_urbanisme.war"
    mode: 0770 
   
- name: Copy addon_urbanisme api properties file
  template:
    src: urbanisme.properties.j2
    dest: "{{ addon_urbanisme_config_directory }}/urbanisme/urbanisme.properties"
    mode: 0770

- name: Copy default api properties file
  template:
    src: default.properties.j2
    dest: "{{ addon_urbanisme_config_directory }}/default.properties"
    mode: 0777

- name: Copy certificate
  copy:
    src: "{{ addon_urbanisme_server_keystore_cert }}"
    dest: "{{ addon_urbanisme_config_directory }}/urbanisme/{{ addon_urbanisme_server_keystore_cert }}"
    mode: 0770
  when: addon_urbanisme_server_keystore_cert | length > 0

- name: Copy entrypoint shell script
  copy:
    src: "entrypoint.sh"
    dest: "{{ addon_urbanisme_image_directory }}/entrypoint.sh"
    mode: 0770

- name: Copy logback.xml
  copy:
    src: logback.xml
    dest: "{{ addon_urbanisme_config_directory }}/urbanisme/logback.xml"
    mode: 0777 

- name: Copy mapfishapp
  copy:
    src: print
    dest: "{{ addon_urbanisme_config_directory }}/urbanisme/templates"
    mode: 0777
  
- name: Build addon_urbanisme api image
  shell: 
    cmd: docker build -t addon_urbanisme-image {{addon_urbanisme_image_directory}}
    chdir: "{{addon_urbanisme_image_directory}}"  

# install yaml-merge
- name: Clone yaml-merge
  shell: 
    chdir: /tmp
    cmd: rm -rf /tmp/yaml-merge; git clone https://github.com/OndraZizka/yaml-merge.git 
    
- name: Override yaml-merge
  copy: 
    src: "YmlMerger.java"
    dest: "/tmp/yaml-merge/src/main/java/org/cobbzilla/util/yml"
    mode: 0664    
    
- name: Build yaml-merge
  shell:
    chdir: /tmp
    cmd: cd yaml-merge ;  mvn -Drelease package

# update docker compose file
- name: Copy addon_urbanisme docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "/tmp/yaml-merge/docker-addon_urbanisme.yml"
    mode: 0664
    
- name: Copy original docker compose file
  copy:
    src: "{{addon_urbanisme_docker_directory}}/docker-compose.yml"
    dest: "/tmp/yaml-merge/docker-compose.yml"
    remote_src: true
    mode: 0664    
    
- name: Merge docker compose file
  shell:
    chdir: "/tmp/yaml-merge"
    cmd: bin/yaml-merge.sh "docker-compose.yml" "docker-addon_urbanisme.yml" > "{{addon_urbanisme_docker_directory}}/docker-compose.yml"
    
#- name: Stop docker compose
#  shell:
#    cmd: docker-compose down
#    chdir: "{{addon_urbanisme_docker_directory}}"
    
- name: Restart docker compose
  shell:
    cmd: docker-compose up -d --build
    chdir: "{{addon_urbanisme_docker_directory}}"