image:
  tag: open-develop
  env:
    - name: URBANISME_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: urbanisme-secret-dev
          key: database.urbanisme.password
    - name: URBANISME_BDD_HOST
      value: 127.0.0.1
      
    - name: SWAGGER_SERVER
      value: https://urbanisme-back-dev.rennes-metropole-georchestra.karbon.open.global