---
# les documents YAML commencent toujours par "---"

# le nom de l'hôte ou groupe concerné
- hosts: all
  vars_files:
    - ~/addon_urbanisme_var.yml
  roles:
    - {
      role: dockerize,
      addon_urbanisme_db_host: '{{db_host}}',
      addon_urbanisme_db_port: '{{db_port}}',
      addon_urbanisme_db_name: '{{db_name}}',
      addon_urbanisme_db_user: '{{db_user}}',
      addon_urbanisme_server_expose_port: '{{server_expose_port}}',
      addon_urbanisme_db_password: '{{db_password}}',
      }
